"use client";

import { ActionIcon, Button, Card, Grid, GridCol, Group, Modal, Pagination, Select, Stack, Table, TableTbody, TableTd, TableTh, TableThead, TableTr, Tabs, Text, TextInput, Title, Tooltip } from "@mantine/core";
import { IconCheck, IconClock, IconEye, IconPlayerPause, IconRefresh } from "@tabler/icons-react";
import { notifications } from "@mantine/notifications";
import { useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import { SubscriptionActionModals } from "@/components/admin/subscription-action-modals";
import { SubscriptionStatusBadge } from "@/components/admin/subscription-status-badge";
import { useAuth } from "@/lib/auth-context";
import { companies, getDaysUntil, getSubscriptionSummary, isExpiringSoon } from "@/lib/mock-data";

function addMonths(dateString, months) {
  const date = new Date(dateString);
  date.setMonth(date.getMonth() + months);
  return date.toISOString().slice(0, 10);
}

function addYears(dateString, years) {
  const date = new Date(dateString);
  date.setFullYear(date.getFullYear() + years);
  return date.toISOString().slice(0, 10);
}

function buildXeroInvoiceNumber(company, index) {
  return `XERO-${company.id.toUpperCase().replace("CMP-", "")}-${String(100 + index).padStart(3, "0")}`;
}

function buildReceiptCode(company, index) {
  return `RCT-${company.id.toUpperCase().replace("CMP-", "")}-${String(200 + index).padStart(4, "0")}`;
}

function buildInvoicePdfUrl(company, index) {
  return `https://example.com/xero/invoices/${company.id}/${index + 1}.pdf`;
}

function buildProofUrl(company, proof) {
  const extension = proof.type === "PDF" ? "pdf" : "jpg";
  return `https://example.com/payments/${company.id}/${proof.id}.${extension}`;
}

function buildInvoiceMeta(company, source = "manual") {
  const suffix = company.id.toUpperCase().replace("CMP-", "");
  return {
    xeroInvoiceStatus: "available",
    xeroInvoiceNumber: `XERO-${suffix}-${source === "cron" ? "AUTO" : "MAN"}-${Date.now().toString().slice(-4)}`,
    xeroInvoicePdfUrl: `https://example.com/xero/invoices/${company.id}/${source}-${Date.now()}.pdf`,
    xeroInvoiceLastSyncAt: new Date().toISOString().slice(0, 16).replace("T", " "),
    xeroInvoiceSyncSource: source,
    xeroInvoiceError: null,
  };
}

function deriveInitialInvoiceState(company, index) {
  const hasOpenInvoiceFlow = ["pending", "temporary", "expired"].includes(company.subscriptionStatus);
  if (!hasOpenInvoiceFlow) {
    return {
      xeroInvoiceStatus: "not-required",
      xeroInvoiceNumber: null,
      xeroInvoicePdfUrl: null,
      xeroInvoiceLastSyncAt: null,
      xeroInvoiceSyncSource: null,
      xeroInvoiceError: null,
    };
  }
  if (index % 3 === 0) {
    return {
      xeroInvoiceStatus: "available",
      xeroInvoiceNumber: `XERO-${company.id.toUpperCase().replace("CMP-", "")}-AUTO-${100 + index}`,
      xeroInvoicePdfUrl: `https://example.com/xero/invoices/${company.id}/auto-${100 + index}.pdf`,
      xeroInvoiceLastSyncAt: "2026-04-20 07:30",
      xeroInvoiceSyncSource: "cron",
      xeroInvoiceError: null,
    };
  }
  return {
    xeroInvoiceStatus: "missing",
    xeroInvoiceNumber: null,
    xeroInvoicePdfUrl: null,
    xeroInvoiceLastSyncAt: "2026-04-20 07:30",
    xeroInvoiceSyncSource: "cron",
    xeroInvoiceError: "Invoice not generated by latest cron run",
  };
}

export default function SubscriptionsPage() {
  const { can } = useAuth();
  const canViewFinanceDetails = can("subscriptions.finance.view");
  const canManageSubscriptions = can("subscriptions.manage");
  const PAGE_SIZE_OPTIONS = ["50", "75", "100"];
  const searchParams = useSearchParams();
  const initialFilterState = useMemo(() => {
    const companyParam = searchParams.get("company");
    const statusParam = searchParams.get("status");
    const allowedStatuses = new Set(["all", "active", "expired", "temporary", "pending"]);
    return {
      query: companyParam || "",
      status: allowedStatuses.has(statusParam || "") ? (statusParam || "all") : "all",
      expiry: "all",
    };
  }, [searchParams]);
  const [rows, setRows] = useState(() =>
    companies.map((company, index) => ({
      ...company,
      ...deriveInitialInvoiceState(company, index),
      xeroInvoiceActionLoading: null,
    })),
  );
  const [queryInput, setQueryInput] = useState(initialFilterState.query);
  const [statusInput, setStatusInput] = useState(initialFilterState.status);
  const [expiryInput, setExpiryInput] = useState(initialFilterState.expiry);
  const [appliedFilters, setAppliedFilters] = useState(initialFilterState);

  const [selectedCompanyId, setSelectedCompanyId] = useState(null);
  const [modalMode, setModalMode] = useState(null);
  const [proofMessagePreview, setProofMessagePreview] = useState(null);
  const [isCronRunning, setIsCronRunning] = useState(false);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(50);

  const filteredRows = useMemo(() => {
    const { query, status, expiry } = appliedFilters;
    return rows.filter((company) => {
      const normalized = query.toLowerCase().trim();
      const queryMatch =
        !normalized ||
        company.name.toLowerCase().includes(normalized) ||
        company.tin.toLowerCase().includes(normalized);
      const statusMatch = status === "all" || company.subscriptionStatus === status;
      const expiryMatch =
        expiry === "all" ||
        (expiry === "expiring-soon" && isExpiringSoon(company.expiryDate)) ||
        (expiry === "expired" && getDaysUntil(company.expiryDate) < 0);
      return queryMatch && statusMatch && expiryMatch;
    });
  }, [rows, appliedFilters]);

  const summary = getSubscriptionSummary(rows);
  const totalCompanies = rows.length;
  const expiring7d = rows.filter((company) => {
    const days = getDaysUntil(company.expiryDate);
    return days >= 0 && days <= 7;
  }).length;
  const expiring1m = rows.filter((company) => {
    const days = getDaysUntil(company.expiryDate);
    return days > 7 && days <= 30;
  }).length;
  const expiring3m = rows.filter((company) => {
    const days = getDaysUntil(company.expiryDate);
    return days > 30 && days <= 90;
  }).length;

  const totalPages = Math.max(1, Math.ceil(filteredRows.length / pageSize));
  const currentPage = Math.min(page, totalPages);
  const paginatedRows = filteredRows.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  const selectedCompany = selectedCompanyId
    ? rows.find((company) => company.id === selectedCompanyId) || null
    : null;

  function openModal(company, mode) {
    setSelectedCompanyId(company.id);
    setModalMode(mode);
  }

  function getExpiryColor(expiryDate) {
    const days = getDaysUntil(expiryDate);
    if (days < 0) return "red";
    if (days <= 7) return "orange";
    return "green";
  }

  function applyAction(action, payload) {
    if (!selectedCompanyId) return;
    setRows((currentRows) =>
      currentRows.map((company) => {
        if (company.id !== selectedCompanyId) return company;

        if (action === "approve") {
          return {
            ...company,
            subscriptionStatus: "active",
            expiryDate: addMonths(payload.paidDate || "2026-04-20", 12),
            lastApprovedPayment: {
              paymentMethod: payload.paymentMethod || "Bank Transfer",
              amount: payload.amount || 620000,
              paidDate: payload.paidDate || "2026-04-20",
              reference: payload.reference || "APR-MOCK",
              proofId: payload.selectedProofId || null,
            },
            subscriptionHistory: [
              {
                year: Number(String(payload.paidDate || "2026-04-20").slice(0, 4)),
                amount: payload.amount || 620000,
                method: payload.paymentMethod || "Bank Transfer",
                reference: payload.reference || "APR-MOCK",
                paymentFlow: "approved-from-proof",
                proofId: payload.selectedProofId || null,
                xeroInvoiceNumber: `XERO-${company.id.toUpperCase().replace("CMP-", "")}-APPROVED`,
                receiptCode: `RCT-${company.id.toUpperCase().replace("CMP-", "")}-APPROVED`,
                invoicePdfUrl: `https://example.com/xero/invoices/${company.id}/approved.pdf`,
              },
              ...company.subscriptionHistory.filter((entry) => !String(entry.reference || "").startsWith("PN-")),
            ],
            xeroInvoiceStatus: "moved-to-history",
            xeroInvoiceNumber: null,
            xeroInvoicePdfUrl: null,
            xeroInvoiceError: null,
          };
        }

        if (action === "renew") {
          const paymentYear = Number(String(payload.paymentDate || "2026-04-20").slice(0, 4));
          const nextProofs =
            payload.proofUploadType === "file" && payload.proofFileName
              ? [
                  {
                    id: `proof-${Date.now()}`,
                    label: payload.proofFileName,
                    uploadedAt: String(payload.paymentDate || "2026-04-20"),
                    type: "PDF",
                  },
                  ...company.paymentProofs,
                ]
              : payload.proofUploadType === "text" && payload.proofTextMessage
                ? [
                    {
                      id: `proof-${Date.now()}`,
                      label: "Payment text message",
                      uploadedAt: String(payload.paymentDate || "2026-04-20"),
                      type: "Text",
                      textMessage: payload.proofTextMessage,
                    },
                    ...company.paymentProofs,
                  ]
                : company.paymentProofs;
          return {
            ...company,
            subscriptionStatus: "active",
            expiryDate: payload.projectedExpiryDate || addYears(company.expiryDate, payload.durationYears || 1),
            lastApprovedPayment: {
              paymentMethod: payload.paymentMethod || company.lastApprovedPayment?.paymentMethod || "LIPA_NAMBA",
              amount: company.lastApprovedPayment?.amount || 620000,
              paidDate: payload.paymentDate || company.lastApprovedPayment?.paidDate || "2026-04-20",
              reference: payload.reference || company.lastApprovedPayment?.reference || "RX-RENEW-MOCK",
              proofId: company.lastApprovedPayment?.proofId || null,
            },
            subscriptionHistory: [
              {
                year: paymentYear,
                amount: 620000,
                method: payload.paymentMethod || "LIPA_NAMBA",
                reference: payload.reference || null,
                remark: payload.remark || null,
                xeroInvoiceNumber: `XERO-${company.id.toUpperCase().replace("CMP-", "")}-RENEW`,
                receiptCode: `RCT-${company.id.toUpperCase().replace("CMP-", "")}-RENEW`,
                invoicePdfUrl: `https://example.com/xero/invoices/${company.id}/renew.pdf`,
              },
              ...company.subscriptionHistory,
            ],
            paymentProofs: nextProofs,
            xeroInvoiceStatus: "moved-to-history",
            xeroInvoiceNumber: null,
            xeroInvoicePdfUrl: null,
            xeroInvoiceError: null,
          };
        }

        if (action === "suspend") {
          return {
            ...company,
            subscriptionStatus: "expired",
            expiryDate: "2026-04-20",
            xeroInvoiceStatus: "missing",
            xeroInvoiceNumber: null,
            xeroInvoicePdfUrl: null,
            xeroInvoiceLastSyncAt: null,
            xeroInvoiceSyncSource: null,
            xeroInvoiceError: "Invoice required for expired subscription",
          };
        }

        if (action === "temporary") {
          return {
            ...company,
            subscriptionStatus: "temporary",
            xeroInvoiceStatus: company.xeroInvoiceStatus === "not-required" ? "missing" : company.xeroInvoiceStatus,
            xeroInvoiceError: company.xeroInvoiceError || "Invoice flow open for temporary status",
          };
        }

        return company;
      }),
    );
  }

  function runInvoiceCronSimulation() {
    if (isCronRunning) return;
    setIsCronRunning(true);
    setTimeout(() => {
      setRows((currentRows) =>
        currentRows.map((company) => {
          if (!["pending", "temporary", "expired"].includes(company.subscriptionStatus)) return company;
          const shouldGenerate = company.id.charCodeAt(company.id.length - 1) % 2 === 0;
          if (shouldGenerate) {
            return { ...company, ...buildInvoiceMeta(company, "cron") };
          }
          return {
            ...company,
            xeroInvoiceStatus: "missing",
            xeroInvoiceNumber: null,
            xeroInvoicePdfUrl: null,
            xeroInvoiceLastSyncAt: new Date().toISOString().slice(0, 16).replace("T", " "),
            xeroInvoiceSyncSource: "cron",
            xeroInvoiceError: "No matching invoice found during cron sync",
          };
        }),
      );
      setIsCronRunning(false);
      notifications.show({
        title: "Cron sync completed",
        message: "Expired subscriptions were synced against mock Xero invoice generation.",
        color: "blue",
      });
    }, 1400);
  }

  function runInvoiceAction(companyId, actionType) {
    setRows((currentRows) =>
      currentRows.map((company) =>
        company.id === companyId
          ? { ...company, xeroInvoiceActionLoading: actionType }
          : company,
      ),
    );

    setTimeout(() => {
      setRows((currentRows) =>
        currentRows.map((company) => {
          if (company.id !== companyId) return company;
          if (!["pending", "temporary", "expired"].includes(company.subscriptionStatus)) {
            return { ...company, xeroInvoiceActionLoading: null };
          }

          if (actionType === "fetch" && company.xeroInvoiceNumber) {
            return { ...company, xeroInvoiceActionLoading: null };
          }

          if (actionType === "search") {
            const found = company.id.charCodeAt(0) % 2 === 0;
            if (found) {
              return {
                ...company,
                ...buildInvoiceMeta(company, "manual"),
                xeroInvoiceActionLoading: null,
              };
            }
            return {
              ...company,
              xeroInvoiceStatus: "missing",
              xeroInvoiceError: "Search completed: invoice not found in Xero",
              xeroInvoiceLastSyncAt: new Date().toISOString().slice(0, 16).replace("T", " "),
              xeroInvoiceActionLoading: null,
            };
          }

          if (actionType === "create") {
            return {
              ...company,
              ...buildInvoiceMeta(company, "manual"),
              xeroInvoiceActionLoading: null,
            };
          }

          return { ...company, xeroInvoiceActionLoading: null };
        }),
      );
    }, 1100);
  }

  function getInvoiceStatusColor(status) {
    if (status === "available") return "green";
    if (status === "missing") return "red";
    if (status === "error") return "red";
    if (status === "syncing") return "blue";
    return "gray";
  }

  return (
    <Stack gap="md">
      <Group justify="space-between">
        <Stack gap={2}>
          <Title order={3}>Subscriptions</Title>
          <Text c="dimmed" size="sm">
            Track active, expired, pending, and temporary accounts.
          </Text>
        </Stack>
        {canViewFinanceDetails ? (
          <Button variant="light" loading={isCronRunning} onClick={runInvoiceCronSimulation}>
            Run Xero cron sync (mock)
          </Button>
        ) : null}
      </Group>

      <Grid>
        <GridCol span={{ base: 6, lg: 3 }}>
          <Card withBorder p="sm">
            <Text size="xs" c="dimmed">
              Subscribed Companies
            </Text>
            <Text fw={700} fz={30}>
              {summary.active}
            </Text>
            <Text size="xs" c="dimmed">
              out of total companies: {totalCompanies}
            </Text>
          </Card>
        </GridCol>
        <GridCol span={{ base: 6, lg: 3 }}>
          <Card withBorder p="sm">
            <Text size="xs" c="dimmed">
              Expired subscriptions
            </Text>
            <Text fw={700} fz={30}>
              {summary.expired}
            </Text>
            <Text size="xs" c="dimmed">
              out of total companies: {totalCompanies}
            </Text>
          </Card>
        </GridCol>
        <GridCol span={{ base: 6, lg: 3 }}>
          <Card withBorder p="sm">
            <Text size="xs" c="dimmed">
              Pending + Temporary
            </Text>
            <Text fw={700} fz={30}>
              {summary.pending + summary.temporary}
            </Text>
            <Text size="xs" c="dimmed">
              Pending {summary.pending} | Temporary {summary.temporary}
            </Text>
          </Card>
        </GridCol>
        <GridCol span={{ base: 6, lg: 3 }}>
          <Card withBorder p="sm">
            <Text size="xs" c="dimmed">
              Expiring in the next
            </Text>
            <Text fw={700} fz={30}>
              {summary.expiringSoon}
            </Text>
            <Text size="xs" c="dimmed">
              7 days {expiring7d} | 1 month {expiring1m} | 3 months {expiring3m}
            </Text>
          </Card>
        </GridCol>
      </Grid>

      <Card withBorder p="sm">
        <Group align="end" grow>
          <TextInput
            label="Company name"
            placeholder="Search name or TIN"
            value={queryInput}
            onChange={(event) => setQueryInput(event.currentTarget.value)}
          />
          <Select
            label="Subscription status"
            value={statusInput}
            onChange={(value) => setStatusInput(value || "all")}
            data={[
              { value: "all", label: "All" },
              { value: "active", label: "Active" },
              { value: "expired", label: "Expired" },
              { value: "temporary", label: "Temporary" },
              { value: "pending", label: "Pending" },
            ]}
          />
          <Select
            label="Expiry"
            value={expiryInput}
            onChange={(value) => setExpiryInput(value || "all")}
            data={[
              { value: "all", label: "All" },
              { value: "expiring-soon", label: "Expiring soon" },
              { value: "expired", label: "Expired" },
            ]}
          />
          <Group gap="xs" style={{ alignSelf: "flex-end" }}>
            <Button
              variant="default"
              onClick={() => {
                setQueryInput("");
                setStatusInput("all");
                setExpiryInput("all");
                setAppliedFilters({ query: "", status: "all", expiry: "all" });
                setPage(1);
              }}
            >
              Reset
            </Button>
            <Button
              onClick={() => {
                setAppliedFilters({
                  query: queryInput,
                  status: statusInput,
                  expiry: expiryInput,
                });
                setPage(1);
              }}
            >
              Apply filters
            </Button>
          </Group>
        </Group>
      </Card>

      <Card withBorder p={0}>
        <Group justify="space-between" p="sm">
          <Text size="sm" c="dimmed">
            {filteredRows.length
              ? `Showing ${(currentPage - 1) * pageSize + 1}-${Math.min(currentPage * pageSize, filteredRows.length)} of ${filteredRows.length} companies`
              : "No companies match current filters"}
          </Text>
          <Group gap="sm">
            <Select
              value={String(pageSize)}
              onChange={(value) => {
                const next = Number(value) || 50;
                setPageSize(next);
                setPage(1);
              }}
              data={PAGE_SIZE_OPTIONS.map((size) => ({ value: size, label: `${size} / page` }))}
              w={120}
            />
            <Pagination value={currentPage} onChange={setPage} total={totalPages} siblings={1} boundaries={1} />
          </Group>
        </Group>
        <Table verticalSpacing="xs" horizontalSpacing="sm" striped highlightOnHover withTableBorder>
          <TableThead>
            <TableTr>
              <TableTh>Company name</TableTh>
              <TableTh>Date joined</TableTh>
              <TableTh>Status</TableTh>
              <TableTh>Expiry date</TableTh>
              <TableTh>Expiring in</TableTh>
              <TableTh>Actions</TableTh>
            </TableTr>
          </TableThead>
          <TableTbody>
            {paginatedRows.map((company) => (
              <TableTr key={company.id}>
                <TableTd>{company.name}</TableTd>
                <TableTd>{company.dateJoined}</TableTd>
                <TableTd>
                  <SubscriptionStatusBadge status={company.subscriptionStatus} expiryDate={company.expiryDate} />
                </TableTd>
                <TableTd>{company.expiryDate}</TableTd>
                <TableTd>
                  <Text size="sm" c={getExpiryColor(company.expiryDate)}>
                    {(() => {
                      const days = getDaysUntil(company.expiryDate);
                      if (days < 0) return `${Math.abs(days)} days ago`;
                      if (days === 0) return "Today";
                      return `${days} days`;
                    })()}
                  </Text>
                </TableTd>
                <TableTd>
                  <Group gap={4} wrap="nowrap">
                    <Tooltip label="View details" withArrow radius="md">
                      <ActionIcon variant="light" color="gray" onClick={() => openModal(company, "view")}>
                        <IconEye size={14} />
                      </ActionIcon>
                    </Tooltip>

                    {canManageSubscriptions && company.subscriptionStatus === "pending" && (
                      <Tooltip label="Approve subscription" withArrow radius="md" color="green">
                        <ActionIcon variant="light" color="green" onClick={() => openModal(company, "approve")}>
                          <IconCheck size={14} />
                        </ActionIcon>
                      </Tooltip>
                    )}

                    {canManageSubscriptions ? (
                      <Tooltip label="Renew subscription" withArrow radius="md" color="blue">
                        <ActionIcon variant="light" color="blue" onClick={() => openModal(company, "renew")}>
                          <IconRefresh size={14} />
                        </ActionIcon>
                      </Tooltip>
                    ) : null}

                    {canManageSubscriptions && company.subscriptionStatus === "expired" && (
                      <Tooltip label="Move to temporary access" withArrow radius="md" color="orange">
                        <ActionIcon variant="light" color="orange" onClick={() => openModal(company, "temporary")}>
                          <IconClock size={14} />
                        </ActionIcon>
                      </Tooltip>
                    )}

                    {canManageSubscriptions &&
                      (company.subscriptionStatus === "pending" || company.subscriptionStatus === "temporary") && (
                      <Tooltip label="Suspend / reject" withArrow radius="md" color="red">
                        <ActionIcon variant="light" color="red" onClick={() => openModal(company, "suspend")}>
                          <IconPlayerPause size={14} />
                        </ActionIcon>
                      </Tooltip>
                    )}
                  </Group>
                </TableTd>
              </TableTr>
            ))}
          </TableTbody>
        </Table>
      </Card>

      <Modal
        opened={modalMode === "view"}
        onClose={() => setModalMode(null)}
        title={selectedCompany ? `${selectedCompany.name} subscription profile` : "Subscription profile"}
        size="80%"
        centered
      >
        {selectedCompany && (
          <Tabs defaultValue="details">
            <Tabs.List>
              <Tabs.Tab value="details">Details</Tabs.Tab>
              {canViewFinanceDetails ? (
                <>
                  <Tabs.Tab value="history">Subscription history</Tabs.Tab>
                  <Tabs.Tab value="proof">Proof of payment</Tabs.Tab>
                </>
              ) : null}
            </Tabs.List>

            <Tabs.Panel value="details" pt="md">
              <Grid>
                <GridCol span={{ base: 12, md: 8 }}>
                  <Card withBorder p="sm">
                    <Stack gap={6}>
                      <Text size="sm">
                        <Text span fw={600}>
                          Company:
                        </Text>{" "}
                        {selectedCompany.name}
                      </Text>
                      <Text size="sm">
                        <Text span fw={600}>
                          TIN:
                        </Text>{" "}
                        {selectedCompany.tin}
                      </Text>
                      <Text size="sm">
                        <Text span fw={600}>
                          Date joined:
                        </Text>{" "}
                        {selectedCompany.dateJoined}
                      </Text>
                    </Stack>
                  </Card>
                </GridCol>
                <GridCol span={{ base: 12, md: 4 }}>
                  <Card withBorder p="sm" h="100%">
                    <Stack gap={8}>
                      <SubscriptionStatusBadge status={selectedCompany.subscriptionStatus} expiryDate={selectedCompany.expiryDate} />
                      <Text size="sm">
                        <Text span fw={600}>
                          Expiry:
                        </Text>{" "}
                        {selectedCompany.expiryDate}
                      </Text>
                      <Text size="sm" c={getExpiryColor(selectedCompany.expiryDate)}>
                        <Text span fw={600}>
                          Time to expiry:
                        </Text>{" "}
                        {(() => {
                          const days = getDaysUntil(selectedCompany.expiryDate);
                          if (days < 0) return `${Math.abs(days)} days ago`;
                          if (days === 0) return "Today";
                          return `${days} days`;
                        })()}
                      </Text>
                    </Stack>
                  </Card>
                </GridCol>
              </Grid>
              {canViewFinanceDetails &&
                ["pending", "temporary", "expired"].includes(selectedCompany.subscriptionStatus) && (
                <Card withBorder p="sm" mt="md">
                  <Group justify="space-between" align="center" mb={8}>
                    <Text fw={700}>Subscription invoice flow (Xero)</Text>
                    {selectedCompany.subscriptionStatus !== "pending" && (
                      <Button size="xs" variant="default" onClick={() => setModalMode("renew")}>
                        Renew subscription
                      </Button>
                    )}
                  </Group>
                  <Grid gutter="sm">
                    <GridCol span={{ base: 12, md: 4 }}>
                      <Text size="xs" c="dimmed">Invoice status</Text>
                      <Text fw={700} tt="capitalize" c={getInvoiceStatusColor(selectedCompany.xeroInvoiceStatus)}>
                        {selectedCompany.xeroInvoiceStatus}
                      </Text>
                    </GridCol>
                    <GridCol span={{ base: 12, md: 4 }}>
                      <Text size="xs" c="dimmed">Recent invoice number</Text>
                      <Text fw={700}>{selectedCompany.xeroInvoiceNumber || "-"}</Text>
                    </GridCol>
                    <GridCol span={{ base: 12, md: 4 }}>
                      <Text size="xs" c="dimmed">Invoice PDF</Text>
                      {selectedCompany.xeroInvoicePdfUrl ? (
                        <Text
                          component="a"
                          href={selectedCompany.xeroInvoicePdfUrl}
                          target="_blank"
                          rel="noreferrer"
                          c="indigo.7"
                          fw={600}
                          size="sm"
                        >
                          Open / Print PDF
                        </Text>
                      ) : (
                        <Text size="sm" c="dimmed">Not available</Text>
                      )}
                    </GridCol>
                    <GridCol span={12}>
                      <Group gap="xs">
                        <Button
                          size="xs"
                          variant="light"
                          loading={selectedCompany.xeroInvoiceActionLoading === "fetch"}
                          onClick={() => runInvoiceAction(selectedCompany.id, "fetch")}
                        >
                          Fetch
                        </Button>
                        <Button
                          size="xs"
                          variant="light"
                          loading={selectedCompany.xeroInvoiceActionLoading === "search"}
                          onClick={() => runInvoiceAction(selectedCompany.id, "search")}
                        >
                          Search
                        </Button>
                        <Button
                          size="xs"
                          variant="default"
                          loading={selectedCompany.xeroInvoiceActionLoading === "create"}
                          onClick={() => runInvoiceAction(selectedCompany.id, "create")}
                        >
                          Create
                        </Button>
                      </Group>
                    </GridCol>
                  </Grid>
                </Card>
              )}
            </Tabs.Panel>

            {canViewFinanceDetails ? (
              <Tabs.Panel value="history" pt="md">
              <Table withTableBorder striped verticalSpacing="xs">
                <TableThead>
                  <TableTr>
                    <TableTh>Year</TableTh>
                    <TableTh>Amount</TableTh>
                    <TableTh>Method</TableTh>
                    <TableTh>Reference</TableTh>
                    <TableTh>Remark</TableTh>
                    <TableTh>Xero invoice</TableTh>
                    <TableTh>Receipt code</TableTh>
                    <TableTh>Invoice PDF</TableTh>
                  </TableTr>
                </TableThead>
                <TableTbody>
                  {selectedCompany.subscriptionHistory.map((entry, index) => {
                    const xeroInvoiceNumber = entry.xeroInvoiceNumber || buildXeroInvoiceNumber(selectedCompany, index);
                    const receiptCode = entry.receiptCode || buildReceiptCode(selectedCompany, index);
                    const invoicePdfUrl = entry.invoicePdfUrl || buildInvoicePdfUrl(selectedCompany, index);
                    return (
                    <TableTr key={`${entry.reference}-${entry.year}-${index}`}>
                      <TableTd>{entry.year}</TableTd>
                      <TableTd>TSh {entry.amount.toLocaleString()}</TableTd>
                      <TableTd>{entry.method}</TableTd>
                      <TableTd>{entry.reference || "-"}</TableTd>
                      <TableTd>{entry.remark || "-"}</TableTd>
                      <TableTd>{xeroInvoiceNumber}</TableTd>
                      <TableTd>{receiptCode}</TableTd>
                      <TableTd>
                        <Text
                          component="a"
                          href={invoicePdfUrl}
                          target="_blank"
                          rel="noreferrer"
                          c="indigo.7"
                          fw={600}
                          size="sm"
                        >
                          Open / Print PDF
                        </Text>
                      </TableTd>
                    </TableTr>
                    );
                  })}
                </TableTbody>
              </Table>
              </Tabs.Panel>
            ) : null}

            {canViewFinanceDetails ? (
              <Tabs.Panel value="proof" pt="md">
              {selectedCompany.paymentProofs.length ? (
                <Table withTableBorder striped verticalSpacing="xs">
                  <TableThead>
                    <TableTr>
                      <TableTh>Label</TableTh>
                      <TableTh>Type</TableTh>
                      <TableTh>Uploaded</TableTh>
                      <TableTh>File</TableTh>
                    </TableTr>
                  </TableThead>
                  <TableTbody>
                    {selectedCompany.paymentProofs.map((proof) => (
                      <TableTr key={proof.id}>
                        <TableTd>{proof.label}</TableTd>
                        <TableTd>{proof.type}</TableTd>
                        <TableTd>{proof.uploadedAt}</TableTd>
                        <TableTd>
                          {proof.type === "Text" ? (
                            <Button
                              size="xs"
                              variant="light"
                              onClick={() => setProofMessagePreview(proof.textMessage || "No message content.")}
                            >
                              View message
                            </Button>
                          ) : (
                            <Text
                              component="a"
                              href={proof.fileUrl || buildProofUrl(selectedCompany, proof)}
                              target="_blank"
                              rel="noreferrer"
                              c="indigo.7"
                              fw={600}
                              size="sm"
                            >
                              Open {proof.type === "PDF" ? "PDF" : "Image"}
                            </Text>
                          )}
                        </TableTd>
                      </TableTr>
                    ))}
                  </TableTbody>
                </Table>
              ) : (
                <Text size="sm" c="dimmed">
                  No proof of payment uploaded.
                </Text>
              )}
              </Tabs.Panel>
            ) : null}
          </Tabs>
        )}
      </Modal>

      {canManageSubscriptions ? (
        <SubscriptionActionModals
          company={selectedCompany}
          opened={Boolean(modalMode) && modalMode !== "view"}
          mode={modalMode}
          onClose={() => setModalMode(null)}
          onApply={applyAction}
        />
      ) : null}

      <Modal
        opened={Boolean(proofMessagePreview)}
        onClose={() => setProofMessagePreview(null)}
        title="Uploaded payment text message"
        centered
      >
        <Text size="sm" style={{ whiteSpace: "pre-wrap" }}>
          {proofMessagePreview}
        </Text>
      </Modal>
    </Stack>
  );
}
